version: '3.3'
services:
  caddy-docker:
    image: nathanosman/caddy-docker
    container_name: caddy-docker
    environment:
    - ACME_EMAIL=[redacted]
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/caddy-docker:/var/lib/caddy-docker
  gogsdb2:
    image: mysql:8.0.12
    container_name: mysqldb
    restart: always
    ports:
    - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
    - db-data:/var/lib/mysql
    - ./mysql_provision:/docker-entrypoint-initdb.d
  gogsapp2:
    image: gogs/gogs
    restart: always
    container_name: gogs
    labels:
    - "caddy.addr=gogs:3000"
    ports:
    - "10022:22"
    - "10080:3000"
    environment:
    - RUN_CROND=true
    volumes:
    - gogs-data:/data
    depends_on:
    - gogsdb2
  jenkinsapp:
    image: jenkinsci/blueocean
    container_name: jenkins
    labels:
    - "caddy.addr=jenkins:8080"
    user: root
    restart: always
    ports:
    - "8080:8080"
    volumes:
    - jenkins-data:/var/jenkings_home
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - gogsdb2
  sonarqube:
    image: sonarqube:7.1
    container_name: sonarqube
    labels:
    - "caddy.addr=sonarqube:9000"
    ports:
    - "9000:9000"
    - "9092:9092"
    environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://mysqldb:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    depends_on:
    - gogsdb2
volumes:
  gogs-data:
    driver: local
  db-data:
    driver: local
  jenkins-data:
    driver: local
